
[mobs]
	blacklist = ["gothic:meatbug_tamed", "gothic:fear_stone", "easy_npc:humanoid", "siegemachines:ballista", "siegemachines:catapult", "siegemachines:battering_ram", "siegemachines:trebuchet", "siegemachines:mortar", "siegemachines:trebuchet", "guardvillagers:guard", "hpm:*", "frozenup:penguin"]
	whitelist = []
	always_show_level = false
	show_level_when_looking_at = true
	exp_bonus_per_level = 0.1
	hidden_levels = []

[attributes]
	attribute_bonuses = [["minecraft:generic.movement_speed", 0.002], ["minecraft:generic.flying_speed", 0.002], ["minecraft:generic.attack_damage", 0.05], ["minecraft:generic.armor", 0.2], ["minecraft:generic.max_health", 0.01], ["autoleveling:monster.projectile_damage_bonus", 0.1], ["autoleveling:monster.explosion_damage_bonus", 0.1]]

[default_leveling_settings]
	starting_level = 1
	max_level = 0
	levels_per_distance = 0.001
	levels_per_deepness = 1.0
	random_level_bonus = 0

